### ISSUE TITLE
2 X Salus

### ISSUE THREAD

**Issue by flcaza** [floringhimie/salusfy#30]
Hi,

If  you need to add 2 Salus:
configuration.yml
```
climate:
  - platform: salusfy
    username: !secret salus_username
    password: !secret salus_password
    id: "1234567890"
  - platform: salusfy_2
    username: !secret salus_username
    password: !secret salus_password
    id: "0987654321"
```

copy directory salusfy from custom_components to salysfy_2

Modify line DOMAIN = "salusfy" with DOMAIN = "salusfy_2" from climate.py

If you have latest version from 

https://github.com/rovingclimber/salusfy

you need to add DOMAIN line between:

```
SUPPORT_FLAGS = ClimateEntityFeature.TARGET_TEMPERATURE

DOMAIN = "salusfy_2"

PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend(

```
